### ISSUE TITLE
Results are not shown and results container is all red

### ISSUE THREAD

**Issue by Mohsin5154** [dotnet/try-samples#82]
![image](https://user-images.githubusercontent.com/41265587/143680938-0d6dd9f9-a778-4da9-a6df-e3c1dc2cc15e.png)

**Comment by r0818405** [comment]
Hi team, same issue here.

**Comment by gill1986** [comment]
Hi Team,

same issue on my machine.

**Comment by OmarVoxel** [comment]
Same! :(

**Comment by TangGuoHua** [comment]
I hit the same issue when i run it on Mac

**Comment by Hultner** [comment]
I also get this issue, both in Chrome and Safari on MacOS 12.2 (Monterey). 
On my laptop running MacOS 10.15 (Catalina) it doesn't start at all.

**Comment by cygnaw** [comment]
Same!

**Comment by VedatAydinKaya** [comment]
same issue

**Comment by yimaiyan** [comment]
same here!

**Comment by ivo-tisljar** [comment]
Same here!

**Comment by nvaghari** [comment]
I was curious about this project but I got same error and I can see this error in Console:
`Uncaught (in promise) Error
    at new t (tsMode.js:1:1)
    at e.<anonymous> (tsMode.js:1:1)
    at w (tsMode.js:1:1)
    at Generator._invoke (tsMode.js:1:1)
    at E.forEach.e.<computed> [as next] (tsMode.js:1:1)
    at s (tsMode.js:1:1)`

**Comment by epiera** [comment]
Hi, same here :(

**Comment by darrencole** [comment]
I got the same problem. It would be great if this resource was working properly.

**Comment by rj-dev** [comment]
Same here :(

**Comment by edmondtchoua** [comment]
Same error

**Comment by The-TallGuy** [comment]
Same here :(

**Comment by devjam1** [comment]
Same 

when I run dotnet try verify I get the below error

```
Unhandled exception: System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 9, the log file has version 14.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 9, the log file has version 14.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 138
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog() in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 127
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\Package.cs:line 112
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\RebuildablePackage.cs:line 22
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Packaging\PackageBuilder.cs:line 163
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext() in D:\workspace\_work\1\s\WorkspaceServer\PackageRegistry.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\PackageRegistry.cs:line 92
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.CompileWorker(Workspace workspace, BufferId activeBufferId, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 412
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.Compile(WorkspaceRequest request, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 193
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.Compile(WorkspaceRequest request, Budget budget) in D:\workspace\_work\1\s\WorkspaceServer\Servers\WorkspaceServerMultiplexer.cs:line 26
   at MLS.Agent.CommandLine.VerifyCommand.Compile(Session session, MarkdownProcessingContext context) in D:\workspace\_work\1\s\MLS.Agent\CommandLine\VerifyCommand.cs:line 193
   at MLS.Agent.CommandLine.VerifyCommand.Do(VerifyOptions verifyOptions, IConsole console, StartupOptions startupOptions, MarkdownProcessingContext context) in D:\workspace\_work\1\s\MLS.Agent\CommandLine\VerifyCommand.cs:line 84
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MLS.Agent.CommandLine.CommandLineParser.<>c__DisplayClass7_0.<<Create>b__2>d.MoveNext() in D:\workspace\_work\1\s\MLS.Agent\CommandLine\CommandLineParser.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I tried the global.json fix suggested in similar raised issues but it didn't work

**Comment by XiangqianChe** [comment]
> I was able to get this working with the SDK 3.1.424 installed alongside of 6.0.402. Had to add a global.json at the root of try-samples like this `{ "sdk": { "version": "3.1.424" } }`
> 
> Removed references to the package 'System.CommandLine.Experimental' from all of the .csproj files. Removed the same references in .\try-samples\101-linq-samples\src\obj\project.assets.json Be sure to update any references to the latest SDK to refer to the 3.1.424, ie: in the project.assets.json... `"runtimeIdentifierGraphPath": "C:\\Program Files\\dotnet\\sdk\\3.1.424\\RuntimeIdentifierGraph.json"`
> 
> The first run will give an error but subsequent runs ran without issue.

Thank you, This Works !!!

**Comment by JasonColeyNZ** [comment]
> 

This worked for me as well thank you

**Comment by thirusanguraja** [comment]
Thank you so much!

**Comment by quangphantally** [comment]
### this should work:

1. check your sdk versions `dotnet --list-sdks`

```
3.0.103 [C:\Program Files\dotnet\sdk]
3.1.426 [C:\Program Files\dotnet\sdk] # <- try this one or any 3.x version
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
7.0.112 [C:\Program Files\dotnet\sdk]
8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
```

2. set sdk version in your repo

```
dotnet new global.json
```

then use the version above. It then should be like this:
```
{
  "sdk": {
    "version": "3.1.426"
  }
}
```

3. install dotnet try tool

```
dotnet tool install --global "Microsoft.dotnet-try"
```

4. verify if any issues

```
dotnet try verify
```

If any, google it

5. enjoy it

```
dotnet try
```

![image](https://github.com/dotnet/try-samples/assets/79438276/c2ed909d-03e5-494f-941f-c8720d6ff511)

**Comment by ghost** [comment]
> ### this should work:
> 1. check your sdk versions `dotnet --list-sdks`
> 
> ```
> 3.0.103 [C:\Program Files\dotnet\sdk]
> 3.1.426 [C:\Program Files\dotnet\sdk] # <- try this one or any 3.x version
> 6.0.202 [C:\Program Files\dotnet\sdk]
> 6.0.203 [C:\Program Files\dotnet\sdk]
> 7.0.112 [C:\Program Files\dotnet\sdk]
> 8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]
> 8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
> ```
> 
> 2. set sdk version in your repo
> 
> ```
> dotnet new global.json
> ```
> 
> then use the version above. It then should be like this:
> 
> ```
> {
>   "sdk": {
>     "version": "3.1.426"
>   }
> }
> ```
> 
> 3. install dotnet try tool
> 
> ```
> dotnet tool install --global "Microsoft.dotnet-try"
> ```
> 
> 4. verify if any issues
> 
> ```
> dotnet try verify
> ```
> 
> If any, google it
> 
> 5. enjoy it
> 
> ```
> dotnet try
> ```
> 
> ![image](https://user-images.githubusercontent.com/79438276/277719550-c2ed909d-03e5-494f-941f-c8720d6ff511.png)

This works. Thanks!!!

**Comment by yanglr** [comment]
I met the similar thing in my Computer too, the issue is solved with below steps:

The enviornment:

**OS**: Win 11

**.NET SDKs**: .NET Core 3.0 SDK, .NET Core 3.1 SDK, .NET 6.0 SDK, .NET 8.0 SDK installed.

## 1.Make sure you installed lastest version of "dotnet try" tool.

If you install it with the command "dotnet tool install -g dotnet-try", you need unistall it first with:

```shell
dotnet tool uninstall -g dotnet-try
```

If you install it with the command "dotnet tool install -g Microsoft.dotnet-try", you need unistall it first with:
```shell
dotnet tool uninstall -g Microsoft.dotnet-try
```

Then install the latest verion of "dotnet try" with below command:
```shell
dotnet tool install -g --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" Microsoft.dotnet-try
```

In Windows, recommand to run above commands in "cmd" with admin permission.

## 2.Make sure you installed .NET 3.0 and .NET 3.1 SDKs
You can run below command to check:
```shell
dotnet --list-sdks
```

If you did not install them, download from below links and install them.

https://dotnet.microsoft.com/en-us/download/dotnet/3.0
https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Note**: .NET core 3.1 SDK's version is "3.1.416" so far.

## 3.Clone code with below command using git shell

```shell
git clone https://github.com/dotnet/try-samples
```

## 4.Create global.json at the root of the folder "try-samples":

The content is below:

```json
{
  "sdk": {
    "version": "3.1.416"
  }
}
```

**Note**: the version "3.1.416" here should be the same as in step 2.

## 5.Try to compile it with "dotnet try verify" command

```shell
cd try-samples/
dotnet try verify
```

If no exceptions happened, jump to next step below.
Else try to remove references to the package 'System.CommandLine.Experimental' from all of the .csproj files.

## 6.Run "dotnet try" command to open the web in browser:

```shell
dotnet try ".\101-linq-samples"
```

## 7.Try the examples from Web.


May it be helpful for you.

---

**References:**

https://github.com/dotnet/try/blob/main/DotNetTryLocal.md

https://github.com/dotnet/try/issues/938#issuecomment-1023604536

This anwer first publish in:
https://stackoverflow.com/a/78534041/6075331
